### ISSUE TITLE
Graph Algorithm Output

### ISSUE THREAD

**Issue by nimishtodi** [flashxio/FlashX#102]
Is there no way to access the component information for the individual vertexes when running a scc algorithm for example? Is this information stored somewhere I am not looking, is there some configuration I should change, or is this something that needs to be implemented separately?

**Comment by zheng-da** [comment]
sorry for the late reply. I saw your email, but was busy, so I didn't respond immediately.

The SCC implementation in FlashGraph returns the component ID for each vertex. However, it's up to the user to perform further computation to get information they want. That's we have FlashGraphR, so users can manipulate the results returned from FlashGraph in R.

Here are a few examples.
    cc <- fg.cluster(fg, "strong")
    # Get the size of each component
    counts <- as.data.frame(table(cc[cc >= 0]))
    # Get the largest component ID
    lcc.id <- as.integer(levels(counts$Var1)[which.max(counts$Freq)])
    # Get all vertices in the largest component
    lcc.v <- which(cc == lcc.id)
    # Get the induced subgraph with all vertices in the largest components
    # Right now, this function is implemented with all data in memory, so run this function with caution.
    sub.fg <- fg.fetch.subgraph(fg, vertices=lcc.v - 1, compress=FALSE)

Does this address your question?

BTW, you can find documents for the FlashGraphR function here:
https://github.com/icoming/FlashGraph/tree/dev/docs/FlashGraphR

**Comment by nimishtodi** [comment]
Yes, this is exactly what I was looking for, thank you for the help.
