### ISSUE TITLE
Reduce # engines in kmeans++

### ISSUE THREAD

**Issue by disa-mhembere** [flashxio/FlashX#139]
Use bcast to activate all when it exists

**Comment by zheng-da** [comment]
@disa-mhembere is this the issue you are targeting?

**Comment by disa-mhembere** [comment]
Well I think this would be solved just by activating all vertices. Is there any reason to not just make a vector with all ids and activate like this pseudocode?

```
vector<vertex_id_t> ids =  range(0, NUM_VERTICES);
vertex_program_object.activate_vertices(&ids[0], NUM_VERTICES)
```

**Comment by zheng-da** [comment]
it might work if you call it in run_on_iteration_end(). but you should make sure only one thread call this.
It's unclear what the performance advantage is. FlashGraph doesn't optimize it, so it still uses message passing and activates individual vertices separately.

**Comment by disa-mhembere** [comment]
Yeah there's also the fact that I have to keep n\* sizeof(vertex_id_t) data
hanging around all at once. Is this true if we activate by start_all?

On Nov 23, 2016 8:21 AM, "Da Zheng" notifications@github.com wrote:

it might work if you call it in run_on_iteration_end(). but you should make
sure only one thread call this.
It's unclear what the performance advantage is. FlashGraph doesn't optimize
it, so it still uses message passing and activates individual vertices
separately.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
https://github.com/flashxio/FlashX/issues/139#issuecomment-262510651, or mute
the thread

**Comment by zheng-da** [comment]
start_all is specifically designed to activate all vertices, so it doesn't require any extra storage. we need activate_all.

**Comment by disa-mhembere** [comment]
ah yeah then this is not done ...

**Comment by disa-mhembere** [comment]
This has a temp fix that uses O(n) memory. Let's open another issue for the actual interface
