### ISSUE TITLE
NMF doesn't converge on a sparse matrix.

### ISSUE THREAD

**Issue by zheng-da** [flashxio/FlashX#150]
The NMF code in R doesn't converge on a sparse matrix.

```
# Get the number of non-zero entries in a sparse matrix.
get.nnz(A) {
    one <- fm.rep.int(1, fm.ncol(A))
    nnzA <- fm.sum(fm.multiply(A, one))
    cat("#nnz of A:", nnzA, "\n")
    one <- NULL
    gc()
    nnzA
}

nnzA <- get.nnz(A)

# trace of W %*% H
trace.MM <- function(W, H) {
    X <- W * fm.t(H)
    fm.sum(X)
}

# ||A - W %*% H||^2
Fnorm <- function(A, W, H) {
    tAW <- fm.multiply(fm.t(A), W)
    tHtWW <- fm.multiply(fm.t(H), fm.multiply(fm.t(W), W))
    # I assume A is a binary sparse matrix.
    # I need to do more if A isn't binary.
    nnzA - 2 * trace.MM(tAW, H) + trace.MM(tHtWW, H)
}

NMF <- function(A, k, niters) {
    eps <- 1e-9
    tA <- fm.t(A)
    n <- fm.nrow(A)
    m <- fm.ncol(A)
    W <- fm.matrix(fm.runif(n * k), n, k)
    H <- fm.matrix(fm.runif(k * m), k, m)

    for (i in 1:niters) {
        den <- fm.multiply(fm.multiply(fm.t(W), W), H)
        H <- fm.pmax2(H * fm.t(fm.multiply(tA, W)), eps) / (den + eps)
        H <- fm.materialize(H)

        den <- fm.multiply(W, fm.multiply(H, fm.t(H)))
        W <- fm.pmax2(W * fm.multiply(A, fm.t(H)), eps) / (den + eps)
        W <- fm.materialize(W)
        gc()
        cat("||A-WH||^2:", Fnorm(A, W, H), "\n")
    }
    list(W=W, H=H)
}
```

**Comment by jovo** [comment]
check against the R NMF.
if should suggest in the documentation an example.
if not, one of the papers on NMF should provide one.

On Mon, Nov 9, 2015 at 9:23 PM, Da Zheng notifications@github.com wrote:

> Get the number of non-zero entries in a sparse matrix.
> 
> get.nnz(A) {
> one <- fm.rep.int(1, fm.ncol(A))
> nnzA <- fm.sum(fm.multiply(A, one))
> cat("#nnz of A:", nnzA, "\n")
> one <- NULL
> gc()
> nnzA
> }
> 
> nnzA <- get.nnz(A)
> trace of W %*% H
> 
> trace.MM <- function(W, H) {
> X <- W \* fm.t(H)
> fm.sum(X)
> }
> ||A - W %*% H||^2
> 
> Fnorm <- function(A, W, H) {
> tAW <- fm.multiply(fm.t(A), W)
> tHtWW <- fm.multiply(fm.t(H), fm.multiply(fm.t(W), W))
> 
> # I assume A is a binary sparse matrix.
> 
> # I need to do more if A isn't binary.
> 
> nnzA - 2 \* trace.MM(tAW, H) + trace.MM(tHtWW, H)
> }
> 
> NMF <- function(A, k, niters) {
> eps <- 1e-9
> tA <- fm.t(A)
> n <- fm.nrow(A)
> m <- fm.ncol(A)
> W <- fm.matrix(fm.runif(n \* k), n, k)
> H <- fm.matrix(fm.runif(k \* m), k, m)
> 
> for (i in 1:niters) {
>     den <- fm.multiply(fm.multiply(fm.t(W), W), H)
>     H <- fm.pmax2(H \* fm.t(fm.multiply(tA, W)), eps) / (den + eps)
>     H <- fm.materialize(H)
> 
> ```
> den <- fm.multiply(W, fm.multiply(H, fm.t(H)))
> W <- fm.pmax2(W * fm.multiply(A, fm.t(H)), eps) / (den + eps)
> W <- fm.materialize(W)
> gc()
> cat("||A-WH||^2:", Fnorm(A, W, H), "\n")
> ```
> 
> }
> list(W=W, H=H)
> 
> }
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/icoming/FlashGraph/issues/150.

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by zheng-da** [comment]
R's NMF can't converge on the same sparse matrix.
Here are a few questions: @jovo 
1. on what matrix do people use R's NMF? R's NMF requires the input matrix doesn't have empty rows or columns.
2. does NMF works better on a symmetric matrix? or it doesn't really matter?
3. how to find a right factorization rank? When the rank is larger, the difference between the original matrix and the product of factorized matrices will be smaller.

**Comment by jovo** [comment]
this seems like we can close this issue?
