### ISSUE TITLE
Install wiki

### ISSUE THREAD

**Issue by disa-mhembere** [flashxio/FlashX#151]
Do we need to add: 
`apt-get install openmpi-bin libopenmpi-dev` for hwloc.h?

**Comment by zheng-da** [comment]
no, hwloc.h is in libhwloc-dev

**Comment by disa-mhembere** [comment]
So lets add:
`libhwloc-dev` to the wiki ?

**Comment by zheng-da** [comment]
sure, but it's only required for FlashGraph in the dev branch.
