### ISSUE TITLE
verify.vs.igrap.R crashes on edgelist read

### ISSUE THREAD

**Issue by disa-mhembere** [flashxio/FlashX#153]
awesomer:release-test disa [disa-dev] $ Rscript verify.vs.igraph.R
Loading required package: igraph
Loading required package: methods

Attaching package: ‘igraph’

The following objects are masked from ‘package:stats’:

```
decompose, spectrum
```

The following object is masked from ‘package:base’:

```
union
```

Loading required package: Rcpp
conf file FlashGraphR.conf doesn't exist.
init FlashGraphR: RAID config file doesn't exist
Run FlashGraphR in standalone mode
Loading required package: MASS
Loading required package: mclust
Package 'mclust' version 5.0.2
Type 'citation("mclust")' for citing this R package in publications.
[1] "The ARI of R kms is 0.00111621632102036"
[1] "The ARI of fg is 0.184083662227963"
[1] "The ARI of R.kms =  0.73023827228347"
[1] "The ARI of fg.kms = 0.716342112683848"
Error in .Call("R_igraph_read_graph_edgelist", file, as.numeric(n), as.logical(directed),  :
  At rinterface.c:4793 : Cannot read edgelist, File operation error
Calls: read.graph -> read.graph.edgelist -> .Call -> <Anonymous>
Execution halted

**Comment by zheng-da** [comment]
It seems the error is in igraph.
I guess it's not FlashGraph error.

**Comment by disa-mhembere** [comment]
disa should not run verify.vs.igraph directly. He should use run_realease_test.sh
