### ISSUE TITLE
try out stuff

### ISSUE THREAD

**Issue by jovo** [flashxio/FlashX#156]
- [x] AWS
- [ ] docker
- [ ] kmeans
- [x] eigs

**Comment by zheng-da** [comment]
I built an AMI for everything.
It's documented here.
http://www.flashgraph.net/documents/get_started2

**Comment by zheng-da** [comment]
FlashX AMI instance is created and is public now.
Users can search for FlashX in community AMIs.

**Comment by jovo** [comment]
that's awesome

On Tue, Jan 19, 2016 at 4:28 PM, Da Zheng notifications@github.com wrote:

> FlashX AMI instance is created and is public now.
> Users can search for FlashX in community AMIs.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/icoming/FlashX/issues/156#issuecomment-172992612.

## 

the glass is all full:  half water, half air.
neurodata.io
