### ISSUE TITLE
incorporate getElbows.R

### ISSUE THREAD

**Issue by jovo** [flashxio/FlashX#171]
this is the R function that youngser uses (saved as txt because github required it).

[getElbows.txt](https://github.com/icoming/FlashX/files/91296/getElbows.txt)

any questions?

**Comment by zheng-da** [comment]
do you need to use it to compute elbows for millions of data points?

**Comment by jovo** [comment]
it helps us choose how many dimensions to keep after doing truncated PCA.
it is an implementation of the attached.

On Thu, Jan 14, 2016 at 11:12 PM, Da Zheng notifications@github.com wrote:

> do you need to use it to compute elbows for millions of data points?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/icoming/FlashX/issues/171#issuecomment-171867668.

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by zheng-da** [comment]
I understand what it does.
I guess i should ask your intention first. Do you want to have it included in FlashR repo?

Since we never need to measure the number of elbows for a large number of dimensions (at most in the order of hundreds), there is no reason to adapt it to use FlashR vectors or matrices.
If we do include it in FlashR, should we have a complete truncated PCA implementation in FlashR as well? It might make more sense.

**Comment by jovo** [comment]
let's talk in person. i'm in my office for another few hours

On Fri, Jan 15, 2016 at 12:54 PM, Da Zheng notifications@github.com wrote:

> I understand what it does.
> I guess i should ask your intention first. Do you want to have it included
> in FlashR repo?
> 
> Since we never need to measure the number of elbows for a large number of
> dimensions (at most in the order of hundreds), there is no reason to adapt
> it to use FlashR vectors or matrices.
> If we do include it in FlashR, should we have a complete truncated PCA
> implementation in FlashR as well? It might make more sense.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/icoming/FlashX/issues/171#issuecomment-172033454.

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by jovo** [comment]
where did it go?

**Comment by zheng-da** [comment]
I secretly hid it :)
https://github.com/icoming/FlashX/blob/dev-zd/Rpkg/R/getElbows.R
should I keep it in the release branch?

**Comment by jovo** [comment]
oh, i don't know, i trust your development process, i just wanted to point
somebody else to it.

what did you think about calling the folder currently called "pureR" -->
"sandbox", and putting it there?

On Mon, Jan 18, 2016 at 10:17 AM, Da Zheng notifications@github.com wrote:

> I secretly hid it :)
> https://github.com/icoming/FlashX/blob/dev-zd/Rpkg/R/getElbows.R
> should I keep it in the release branch?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/icoming/FlashX/issues/171#issuecomment-172556962.

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by zheng-da** [comment]
sounds better
