### ISSUE TITLE
draft response to NINCONPUTES

### ISSUE THREAD

**Issue by jovo** [flashxio/FlashX#173]
https://www.fbo.gov/index?s=opportunity&mode=form&tab=core&id=7ea2ad0e075b31c05a011f2d835392a9

**Comment by zheng-da** [comment]
sorry, I'll read some materials and give you a draft by this week.

**Comment by jovo** [comment]
don't be sorry! you said you have something to say, let's say it!

On Fri, Jan 15, 2016 at 12:55 PM, Da Zheng notifications@github.com wrote:

> sorry, I'll read some materials and give you a draft by this week.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/icoming/FlashX/issues/173#issuecomment-172033648.

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by zheng-da** [comment]
I try to not say something stupid :)
