### ISSUE TITLE
implement LOL in FlashR

### ISSUE THREAD

**Issue by zheng-da** [flashxio/FlashX#175]

**Comment by zheng-da** [comment]
Do you need QR decomposition? @jovo

**Comment by jovo** [comment]
happy to be without it for a first version.
experiments demonstrate that it is not that important.

On Fri, Jan 15, 2016 at 2:11 PM, Da Zheng notifications@github.com wrote:

> Do you need QR decomposition? @jovo https://github.com/jovo
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/icoming/FlashX/issues/175#issuecomment-172056565.

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by jovo** [comment]
can you add pseudocode for FlashR implementation of LOL into an appendix in
the paper please?

On Wed, May 11, 2016 at 11:14 AM, Da Zheng notifications@github.com wrote:

> Closed #175 https://github.com/zheng-da/FlashX/issues/175.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/zheng-da/FlashX/issues/175#event-657322672

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by zheng-da** [comment]
sure. I'll just provide R code of LOL. It's not long.
