### ISSUE TITLE
webpage updates

### ISSUE THREAD

**Issue by jovo** [flashxio/FlashX#183]
- [ ] redirect http://www.flashgraph.net/ to flashx website
- [x] put link to github in the flashx repo

**Comment by zheng-da** [comment]
flashgraph.net is redirected to flashx.io.
i need to figure out how www.flashgraph.net is set up.

Do you mean having a link to the github repo in FlashX.io?

**Comment by jovo** [comment]
great & yes.
thanks, j

On Tue, Jan 19, 2016 at 4:47 PM, Da Zheng notifications@github.com wrote:

> flashgraph.net is redirected to flashx.io.
> i need to figure out how www.flashgraph.net is set up.
> 
> Do you mean having a link to the github repo in FlashX.io?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/icoming/FlashX/issues/183#issuecomment-172997802.

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by disa-mhembere** [comment]
i also _now_ get that flashx.io redirect issue you had before @icoming on my home computer :(

**Comment by zheng-da** [comment]
have any ideas why it happens?

**Comment by disa-mhembere** [comment]
I've never experienced this before. It might be how gh-pages is handling redirects. I'm not sure what tool can tell us what's going on.

**Comment by zheng-da** [comment]
i might have messed up url redirection in GoDaddy.
I tried to use subdomain forwarding in GoDaddy to redirect www.flashgraph.net to flashx.io.
but it doesn't work as I expected. Does GoDaddy treats www. subdomain differently?

**Comment by zheng-da** [comment]
the forwarding for flashgraph.net works fine.

**Comment by disa-mhembere** [comment]
I'm not an authority on this, but kunal is i think. Let's loop him in on this tomorrow.

**Comment by zheng-da** [comment]
@jovo @disa-mhembere can you try www.flashgraph.net now?
I'm not sure if I messed up something. in chrome, even if i input flashx.io, i always gets some webpage of godaddy

**Comment by jovo** [comment]
words for me.

On Thu, Jan 21, 2016 at 4:41 PM, Da Zheng notifications@github.com wrote:

> @jovo https://github.com/jovo @disa-mhembere
> https://github.com/disa-mhembere can you try www.flashgraph.net now?
> I'm not sure if I messed up something. in chrome, even if i input
> flashx.io, i always gets some webpage of godaddy
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/icoming/FlashX/issues/183#issuecomment-173717102.

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by zheng-da** [comment]
it works for me as well now.

**Comment by disa-mhembere** [comment]
Doesn't work for me :/

**Comment by zheng-da** [comment]
this is weird. try safari or firefox?

**Comment by disa-mhembere** [comment]
Yeah it's a chrome thing. I dropped my cache and it works
