### ISSUE TITLE
set css for the tutorials in flashx.io

### ISSUE THREAD

**Issue by zheng-da** [flashxio/FlashX#191]

**Comment by disa-mhembere** [comment]
i cannot even get to flashx.io. What's the github.io url again?

**Comment by zheng-da** [comment]
it's basically the FlashX github.
the stuff is in the gh-pages branch.

**Comment by disa-mhembere** [comment]
yes i know, but when i push i want to make sure it does what it's meant to so i need some non-local url that is not flash.io

**Comment by zheng-da** [comment]
is http://icoming.github.io/FlashX/ what you are asking?

**Comment by disa-mhembere** [comment]
yes! thanks

**Comment by disa-mhembere** [comment]
jekyll resolved
