### ISSUE TITLE
add acknolwedgements to arxiv pubs

### ISSUE THREAD

**Issue by jovo** [flashxio/FlashX#199]
"This work is graciously supported by the Defense Advanced Research Projects Agency (DARPA) SIMPLEX program through SPAWAR contract N66001-15-C-4041 and DARPA GRAPHS N66001-14-1-4028."

@jovo @randburns @disa-mhembere

**Comment by zheng-da** [comment]
which one? I have added acknowledgements to the recent two arxiv papers.

**Comment by jovo** [comment]
Ok. Then this issue is closed :)

On Tuesday, March 1, 2016, Da Zheng notifications@github.com wrote:

> which one? I have added acknowledgements to the recent two arxiv papers.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/zheng-da/FlashX/issues/199#issuecomment-190753682.

## 

the glass is all full:  half water, half air.
neurodata.io
