### ISSUE TITLE
[FlashEigen] No external memory?

### ISSUE THREAD

**Issue by manpen** [flashxio/FlashX#231]
I want to use FlashEigen (release branch or version 0.3.1) on a large (currently 1e8 edges) undirected graph with a small average degree of 1 to 1.01. FlashX is installed with trillinos and R support. The R code used is the follows the documention:

> library(FlashR)
> fg.set.conf("...")
> m <- fm.load.matrix(...)
> multiply <- function(x, extra) m %*% x
> res <- fm.eigen(multiply, options=list(n=dim(m)[1], nev=16))

The system has 4x 512GB SSDs configured and 32 GB RAM. After roughly one minute of execution, the system's main memory is fully allocated and swapping begins -- of course, now the computation become prohibitive expensive.

Looking through the R binding, it seems, that in file Rpkg/src/matrix_interface.cpp in function R_FM_eigen the option opts.in_mem remains on its default value which is true. If one sets it to false in the CPP file, the fm.eigen call causes a SEGFAULT.

On a smaller instance (which is still solvable in internal memory), I get the following output: 

```
the first part is in {path to SSD} -- repeats often

================================================================================

                         BlockKrylovSchur Solver Status

The solver is initialized.
The number of iterations performed is 192
The block size is         1
The number of blocks is   32
The current basis size is 32
The number of auxiliary vectors is 0
The number of operations Op*x   is 192

CURRENT RITZ VALUES             
          Ritz Value       Ritz Residual
--------------------------------------------------------------------------------
        3.754535e+00        0.000000e+00
       -3.754535e+00        4.029045e-16
       -3.754535e+00        2.690149e-16
        3.754535e+00        4.080005e-16
       -3.210159e+00        1.111697e-13
        3.210159e+00        2.522337e-16
        3.210159e+00        8.944722e-15
       -3.210159e+00        1.014202e-15
       -3.178701e+00        1.079908e-12
       -3.178701e+00        4.614257e-17
        3.178701e+00        4.145138e-13
        3.178701e+00        1.083455e-16
       -3.089983e+00        1.453472e-14
        3.089983e+00        1.830781e-08
        3.089983e+00        5.811500e-15
       -3.089983e+00        2.663849e-08

================================================================================

================================================================================

                      TimeMonitor results over 1 processor

Timer Name                                           Global time (num calls)    
--------------------------------------------------------------------------------
Anasazi: BlockKrylovSchur::Computing Ritz vectors    3.524 (1)                  
Anasazi: BlockKrylovSchur::Computing Schur form      0.005397 (11)              
Anasazi: BlockKrylovSchur::Operation Op*x            19.33 (192)                
Anasazi: BlockKrylovSchur::Orthogonalization         962.7 (193)                
Anasazi: BlockKrylovSchur::Sorting Ritz values       3.6e-05 (11)               
Anasazi: BlockKrylovSchur::Sorting Schur form        0.001468 (11)              
Anasazi: BlockKrylovSchurSolMgr restarting           33.51 (10)                 
Anasazi: BlockKrylovSchurSolMgr::solve()             1052 (1)                   
================================================================================
the first part is in {path to ssd}
Out of boundary

 *** caught segfault ***
address (nil), cause 'memory not mapped'

Traceback:
 1: .Call("R_FM_eigen", as.function(func), extra, as.logical(sym),     as.list(options), PACKAGE = "FlashR")
 2: fm.eigen(multiply, options = list(n = dim(m)[1], nev = 16))
```

Is EM supported in R, if not, which interface can be used for FlashEigen ?

Thank  you!

**Comment by zheng-da** [comment]
Your graph is really sparse. It's not really the ideal graph that FlashEigen is designed for.
If many of the vertices don't have edges, you can remove these empty vertices first and construct a new graph with fg.fetch.subgraph.

I assume you have set up SAFS.
When you load the graph or matrix with fm.load.matrix, the parameter in.mem of the function controls where to keep the matrix. You should set in.mem=FALSE

It's weird you run into memory error even if a graph is small enough to be solved in memory.

**Comment by manpen** [comment]
First of all: Thank you for the fast response! If I set in.mem to FALSE, the computation of some larger matrices works out. For other very sparse graphs with matrices of ~4GB the issue remains. I will look into it, as soon as I can.

**Comment by zheng-da** [comment]
The R interface of FlashEigen cannot control where the vector subspace is stored. In the current implementation, the vector subspace is stored in memory.
If you use its C++ interface, you can force the vector subspace to be stored on disks. Ideally, the eigensolver should automatically determine how the subspace is stored.
In your very sparse matrix (~4GB), how many rows/columns are there?
