### ISSUE TITLE
[Flash Graph] Preprocessing fails

### ISSUE THREAD

**Issue by a-yasar** [flashxio/FlashX#232]
Hi, I would like to run several graph algorithms on a ~2billion(~20G) edge graph with FlashGraph. I have a server which has 16 cores, 32gb of memory 2*240GB SSD and 2TB HDD. However when I run el2fg tool to convert edge list into flashgraph format system fails. I changed configuration files as described in the tutorial and also I add another ssd and mount it as swap. However when I run el2fg memory usage exceeds 30G and virtual memory usage exceeds 80G and after a while system kills itself. Am I doing something wrong? Have you ever encountered with such a problem?

**Comment by zheng-da** [comment]
Hi, I think you probably didn't give the option "-e" to el2al.
Could you point me to the tutorial you followed? I need to fix the tutorial. Thanks.

**Comment by a-yasar** [comment]
Thanks for help. I followed quick start tutorial: https://github.com/zheng-da/FlashX/wiki/FlashX-Quick-Start-Guide. Now when I add -e flag it throws that exception:  "terminate called after throwing an instance of 'safs::io_exception'
  what():  The I/O object can't write data. offset: 0, size: 5181440"

**Comment by zheng-da** [comment]
Could you show me the FlashGraph config file and the data config file (the file specified by "root_conf")?
When you specify the path to the data config file and the paths to the directories on SSDs, it's better to use absolute paths.

**Comment by a-yasar** [comment]
Hello, thanks again for your help. My config file is as follows:

`RAID_mapping=RAID0`
`io_depth=64`
`cache_size=512M`
`num_nodes=1`
`root_conf=/home/ayasar/FlashGraph/flash-graph/conf/data_files.txt`
`num_io_threads=1`
`threads=12`
`serial_run=`

and my data file:

`0:/home/ayasar/FlashGraph/flash-graph/data`
`0:/home/ayasar/disk1`
`0:/home/ayasar/disk2`

**Comment by a-yasar** [comment]
An update:

When I add 'writable' keyword to config file FG started to preprocessing. However after a while it threw that exception:

`matrix/fm_utils.cpp:665:` fg::FG_graph::ptr fm::create_fg_graph(const string&, fm::edge_list::ptr): `Assertion` `ret' failed.
`Aborted` (core dumped)

before throwing this exception last status update is as follows:

`It` takes 0.245 seconds to construct the graph index
`the` first part is in /.../...../veckcvC3dPW

**Comment by a-yasar** [comment]
`SOLVED`

**Comment by zheng-da** [comment]
Great!
I wanted to suggest you that you need 'writable' in the config file, but you were quick. :)
I have made a change to allow writing data to SAFS by default.

As you may have found out, your second error was caused by the failure of renaming the temporary file on SAFS. I also changed the code to print error messages to help users figure out where the problem is.
I'm a little curious why renaming fails in your case?
