### ISSUE TITLE
What graph metrics exist in FlashX?

### ISSUE THREAD

**Issue by gkiar** [flashxio/FlashX#237]
The wiki home page points to a page [here](https://github.com/zheng-da/FlashX/wiki/Graph-algorithms-in-FlashGraph), where and enumeration of the graph metrics incorporated are supposed to live. The page is, however, blank. My question is, what graph metrics _are_ in FlashX? Thanks! :)

**Comment by zheng-da** [comment]
will this be what you are looking for?
https://github.com/zheng-da/FlashX/wiki/FlashGraphR-programming-tutorial#the-graph-algorithms

**Comment by gkiar** [comment]
Yup! You'll probably want to fix the broken link on this page: https://github.com/zheng-da/FlashX/wiki 

Thanks!
