### ISSUE TITLE
In FlashX Quic Start, I found an omitted word.

### ISSUE THREAD

**Issue by kckjn97** [flashxio/FlashX#238]
In FlashX Quic Start, I found an omitted word and step.
(https://github.com/zheng-da/FlashX/wiki/FlashX-Quick-Start-Guide)
1. an omitted word in "Run FlashGraph"
   build/matrix/utils/el2fg conf/run_test.txt wiki-Vote.txt wiki-Vote
   ->
   build/matrix/utils/el2fg flash-graph/conf/run_test.txt wiki-Vote.txt wiki-Vote
2. in Step2 "Step 2: Load graph files to SAFS",
   I experienced an error. ("/root/FlashX-3.1/flash-graph/data' doesn't exist")
   Before Step2, I should have made an directory.
   -> "mkdir flash-graph/data"

Thank you.

**Comment by zheng-da** [comment]
Thank you for your suggestions. I have included them in the wiki.
