### ISSUE TITLE
weighted graph conversion

### ISSUE THREAD

**Issue by gkiar** [flashxio/FlashX#249]
I would like to use weighted graphs in FlashX, but cannot figure out how to convert them to the spec. An example graph can be found [here](http://openconnecto.me/mrdata/share/dti/ndmg_v0011/KKI2009/desikan/KKI2009_142_2_DTI_desikan.graphml). Thanks!

**Comment by zheng-da** [comment]
Please check out this. Is it clear how to construct a graph with edge attributes?
https://github.com/zheng-da/FlashX/wiki/FlashX-Quick-Start-Guide#convert-a-graph-in-edge-list-format-to-the-flashgraph-format

After constructing a graph with edge attributes, what are you going to do?
The existing implementations of graph algorithms don't use edge attributes for computation.
