### ISSUE TITLE
top 10 algs

### ISSUE THREAD

**Issue by jovo** [flashxio/FlashX#325]
http://www.kdnuggets.com/2016/08/10-algorithms-machine-learning-engineers.html

seems like we should have all of these?

@zheng-da

**Comment by zheng-da** [comment]
We definitely should have them in FlashR-learn.

No. 1 I guess random forest is more useful than this.

No. 2 I can get naive bayes from e1071.

No. 3 is ridge regression (linear regression with ridge loss)? Do you know what R package that can do things like glmnet, but is implemented in R? If we have such an R package, we will have mature implementations for both No. 3 and No. 4. We want LASSO as well, right?

No 5. How should we get a good SVM R implementation? Do you know anyone who can help us with it?

No 6. I don't know what this really is. I'll study it.

No 7. What are the popular clustering algorithms out there? I know k-means is one of them. What else?

No 8. Done. FlashR has a PCA implementation, but you should check if it works as you expect when I come back.

No 9. Done.

No. 10. e1071 has an implementation. I'll port it.

I'll make a plan for this as well.

**Comment by jovo** [comment]
1. agreed
2. agreed.
3. yes ridge regression equals regression with ridge loss.  glment is an R package, a very popular one. i don't care about lasso (it doesn't work well in practice), but lots of other people do.
4. see above
5. nope.  maybe daniel robinson?
6. RF & xgboost are the only important ensemble methods
7. k-means, gmm, hierarchical versions of both, spectral clustering (which does pca first, then kmeans or gmm)
8. ok
9. great
10. ok

let's put this in the 1 year plan. seems totally doable, especially with a new hire whose job it is to do it :)
