### ISSUE TITLE
Why the output “cache hits” is always 0?

### ISSUE THREAD

**Issue by dreamedcheng** [flashxio/FlashX#327]
Hi, 

When I running algorithms, e.g., PR2 and BFS by using flashgraph. The output "cache hits" is always 0, even when I use different datasets (ranging from 11GB to 50GB in binary edge list format). The page cache size for SAFS is set to 12GB (total 32GB memory). Is that result reasonable or what's the problem with that?

Thank you in advance?

**Comment by zheng-da** [comment]
It does sound weird. Below shows the output when I run BFS on the twitter graph stored in SAFS. Could you show me the output of FlashGraph?

```
zhengda@awesomer:~/FlashGraph-dev$ flash-graph/test-algs/test_algs matrix/conf/run_test.txt twitter.adj twitter.index bfs -s 12
SAFS runs on 4 NUMA nodes
The root conf file: /mnt/nfs/zhengda/FlashX/conf/data_files.txt
There are 3 nodes with disks
SAFS runs on 24 SSDs with 24 I/O threads
FlashGraph runs on 64 threads and 4 nodes
Configuration parameters in graph algorithm.
        threads: 64
        prof_file:
        trace_file:
        max_processing_vertices: 2000
        enable_elevator: 0
        part_range_size_log: 10
        preload: 0
        index_file_weight: 10
        in_mem_graph: 0
        num_vparts: 1
        min_vpart_degree: 2147483647
        serial_run: 0
        vertex_merge_gap: 0
allocate 165782632 bytes for vertex index
init from a compressed vertex index
There are 915394 large in-vertices and 563663 large out-vertices
init in-mem compressed index takes 0.31763 seconds
There are 61578415 vertices
It takes 0.39428 seconds to initialize the graph engine
BFS starts
Iter 0 takes 0.202156 seconds, and 1001061 vertices are in iter 1
Iter 1 takes 1.35599 seconds, and 16573821 vertices are in iter 2
Iter 2 takes 2.00867 seconds, and 31511638 vertices are in iter 3
Iter 3 takes 1.46014 seconds, and 25600883 vertices are in iter 4
Iter 4 takes 1.02641 seconds, and 4948395 vertices are in iter 5
Iter 5 takes 0.373213 seconds, and 833632 vertices are in iter 6
Iter 6 takes 0.042604 seconds, and 93998 vertices are in iter 7
Iter 7 takes 0.007392 seconds, and 10225 vertices are in iter 8
Iter 8 takes 0.002388 seconds, and 1126 vertices are in iter 9
Iter 9 takes 0.001558 seconds, and 385 vertices are in iter 10
Iter 10 takes 0.002497 seconds, and 141 vertices are in iter 11
Iter 11 takes 0.001732 seconds, and 140 vertices are in iter 12
Iter 12 takes 0.001943 seconds, and 7 vertices are in iter 13
Iter 13 takes 0.001716 seconds, and 0 vertices are in iter 14
The graph engine takes 6.58433 seconds to complete
twitter.adj gets 1832132 async I/O accesses, 14294666144 in bytes
There are 5255048 pages accessed, 963596 cache hits, 24957 of them are in the fast process
BFS from v12 traverses 35016137 vertices on edge type 2
I/O system is destroyed
I/O threads get 1658658 reads (17743572992 bytes) and 0 writes (0 bytes)
```

**Comment by dreamedcheng** [comment]
Here is the output when running BFS on twitter
SAFS runs on 1 NUMA nodes
The root conf file: /home/wcw/FlashX/flash-graph/conf/data_files.txt
There are 1 nodes with disks
SAFS runs on 2 SSDs with 2 I/O threads
FlashGraph runs on 8 threads and 1 nodes
Configuration parameters in graph algorithm.
    threads: 8
    prof_file:
    trace_file:
    max_processing_vertices: 2000
    enable_elevator: 0
    part_range_size_log: 10
    preload: 0
    index_file_weight: 10
    in_mem_graph: 0
    num_vparts: 1
    min_vpart_degree: 2147483647
    serial_run: 1
    vertex_merge_gap: 0
allocate 165782632 bytes for vertex index
init from a compressed vertex index
There are 915394 large in-vertices and 563663 large out-vertices
init in-mem compressed index takes 0.477658 seconds
There are 61578415 vertices
It takes 0.620791 seconds to initialize the graph engine
BFS starts
Iter 0 takes 0.051079 seconds, and 1001061 vertices are in iter 1
Iter 1 takes 5.37605 seconds, and 16573821 vertices are in iter 2
Iter 2 takes 7.69569 seconds, and 31511638 vertices are in iter 3
Iter 3 takes 3.05429 seconds, and 25600883 vertices are in iter 4
Iter 4 takes 0.910768 seconds, and 4948395 vertices are in iter 5
Iter 5 takes 0.227649 seconds, and 833632 vertices are in iter 6
Iter 6 takes 0.060508 seconds, and 93998 vertices are in iter 7
Iter 7 takes 0.010099 seconds, and 10225 vertices are in iter 8
Iter 8 takes 0.01315 seconds, and 1126 vertices are in iter 9
Iter 9 takes 0.001 seconds, and 385 vertices are in iter 10
Iter 10 takes 0.001016 seconds, and 141 vertices are in iter 11
Iter 11 takes 0.001015 seconds, and 140 vertices are in iter 12
Iter 12 takes 0.000987 seconds, and 7 vertices are in iter 13
Iter 13 takes 0.000782 seconds, and 0 vertices are in iter 14
The graph engine takes 17.4117 seconds to complete
twitter.adj gets 1537817 async I/O accesses, 14609666064 in bytes
There are 5032690 pages accessed, 0 cache hits, 309017 of them are in the fast process
BFS from v12 traverses 35016137 vertices on edge type 2
I/O system is destroyed
I/O threads get 534005 reads (6722727936 bytes) and 0 writes (0 bytes)

**Comment by zheng-da** [comment]
Thank you. I have fixed the bug and pushed the fix to the release branch.
could you please pull it and test if it works for you? thanks

**Comment by dreamedcheng** [comment]
Thank you! 
I'll try it.

**Comment by dreamedcheng** [comment]
Now the output is normal.
