### ISSUE TITLE
FlashGraph crashes on weighted graph BOTH_EDGES iterator request.

### ISSUE THREAD

**Issue by disa-mhembere** [flashxio/FlashX#62]
Given a graph with a count attribute. The following causes an abort.

`edge_seq_iterator id_it = vertex.get_neigh_seq_it(BOTH_EDGES);`

also, 

`safs::page_byte_array::seq_const_iterator<edge_count> data_seq_iterator count_it =
            ((const page_directed_vertex&)vertex).get_data_seq_it<edge_count>(BOTH_EDGES);`

**NOTE**: `IN_EDGE` & `OUT_EDGE` both work.

**Comment by zheng-da** [comment]
It was done this way intentionally. in-edge list and out-edge list are stored separately. It'll be more costly if they are accessed in one iterator.

**Comment by zheng-da** [comment]
I'll make the error more understandable by throwing an exception.

**Comment by disa-mhembere** [comment]
Oh ok. That makes sense.
