### ISSUE TITLE
k-means with R bindings

### ISSUE THREAD

**Issue by jovo** [flashxio/FlashX#7]
also kmeans++ and kmeans||

**Comment by jovo** [comment]
how do i add labels?

**Comment by zheng-da** [comment]
you can add labels and assign the task to someone on the right. see Labels and Assignee?

**Comment by jovo** [comment]
maybe cuz i don't own FlashGraph i can't make such assignments?

On Wed, Nov 5, 2014 at 8:58 AM, Da Zheng notifications@github.com wrote:

>  you can add labels and assign the task to someone on the right. see
> Labels and Assignee?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/icoming/FlashGraph/issues/7#issuecomment-61810079.

## 

it's our dream
openconnecto.me, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by disa-mhembere** [comment]
I think you just have to add jovo as a contributor da

**Comment by zheng-da** [comment]
jovo, you are a contributor now. can you try again

**Comment by jovo** [comment]
ok. will try. thanks. 

—
