### ISSUE TITLE
create a website for FlashGraph

### ISSUE THREAD

**Issue by zheng-da** [flashxio/FlashX#70]

**Comment by jovo** [comment]
where?

On Wednesday, May 20, 2015, Da Zheng notifications@github.com wrote:

>  Closed #70 https://github.com/icoming/FlashGraph/issues/70.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/icoming/FlashGraph/issues/70#event-310043383.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by zheng-da** [comment]
http://www.flashgraph.net/
