### ISSUE TITLE
Check undirected graph creation

### ISSUE THREAD

**Issue by disa-mhembere** [flashxio/FlashX#83]
flash-graph/tools/el2al -u -v -w flash-graph/data/wiki-Vote-adj flash-graph/data/wiki-Vote-index flash-graph/data/wiki-Vote.txt

test_algs: vertex_compute.cpp:252: virtual void fg::merged_undirected_vertex_compute::run(safs::page_byte_array&): Assertion `pg_v.get_id() == id' failed.
Aborted (core dumped)

**Comment by zheng-da** [comment]
FlashGraph assumes that there is at most one edge between two vertices in an undirected graph. When el2al treats a directed graph as an undirected graph, there might be two edges between two vertices. el2al should check if duplicated edges exist when converting an edge list to the FlashGraph format.
